# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

acfd <- function(d, z, Chr, Dist) {
    .Call(`_Fantasio2_acfd`, d, z, Chr, Dist)
}

checkOpenMP <- function() {
    .Call(`_Fantasio2_checkOpenMP`)
}

festim <- function(p_A, p, submap, deltaDist, epsilon, f_start, a_start) {
    .Call(`_Fantasio2_festim`, p_A, p, submap, deltaDist, epsilon, f_start, a_start)
}

forward_backward <- function(logEmiss, Dist, a, f) {
    .Call(`_Fantasio2_forward_backward`, logEmiss, Dist, a, f)
}

logLikelihood_gradient <- function(logEmiss, Dist, a, f) {
    .Call(`_Fantasio2_logLikelihood_gradient`, logEmiss, Dist, a, f)
}

logEmiss <- function(Y1, Y2, logFreq, epsilon) {
    .Call(`_Fantasio2_logEmiss`, Y1, Y2, logFreq, epsilon)
}

logitModel <- function(Y, X, H, beg, end) {
    .Call(`_Fantasio2_logitModel`, Y, X, H, beg, end)
}

m4_logEmiss <- function(p_A, p, map, epsilon) {
    .Call(`_Fantasio2_m4_logEmiss`, p_A, p, map, epsilon)
}

maxGaussianGenome <- function(nSimus, lambda, sigma, dist, len, seed, nThreads = 4L) {
    .Call(`_Fantasio2_maxGaussianGenome`, nSimus, lambda, sigma, dist, len, seed, nThreads)
}

getSeed <- function() {
    .Call(`_Fantasio2_getSeed`)
}

setSeed <- function(seed) {
    invisible(.Call(`_Fantasio2_setSeed`, seed))
}

mt_runif <- function() {
    .Call(`_Fantasio2_mt_runif`)
}

probaHBD <- function(p_A, p, submap, deltaDist, whichInds, a, f, epsilon) {
    .Call(`_Fantasio2_probaHBD`, p_A, p, submap, deltaDist, whichInds, a, f, epsilon)
}

randomSnp <- function(L) {
    .Call(`_Fantasio2_randomSnp`, L)
}

setUserParam <- function(m, epsilon, past, delta, max_iterations, max_submin, max_linesearch, min_step, max_step, ftol, wolfe, max_retries, lower, upper, n_threads, use_float, debug, verbose, use_froh, minNbSNPs, minROHlength, minDistHet, maxGapLength) {
    invisible(.Call(`_Fantasio2_setUserParam`, m, epsilon, past, delta, max_iterations, max_submin, max_linesearch, min_step, max_step, ftol, wolfe, max_retries, lower, upper, n_threads, use_float, debug, verbose, use_froh, minNbSNPs, minROHlength, minDistHet, maxGapLength))
}

getUserParam <- function() {
    .Call(`_Fantasio2_getUserParam`)
}

testForwardBackward <- function(p_A, p_, submap_, deltaDist, epsilon, i, a, f) {
    .Call(`_Fantasio2_testForwardBackward`, p_A, p_, submap_, deltaDist, epsilon, i, a, f)
}

testLikelihood <- function(p_A, p_, map_, deltaDist, epsilon, i, a, f) {
    .Call(`_Fantasio2_testLikelihood`, p_A, p_, map_, deltaDist, epsilon, i, a, f)
}

testLogEmiss <- function(p_A, p_, map_, epsilon, i) {
    .Call(`_Fantasio2_testLogEmiss`, p_A, p_, map_, epsilon, i)
}

testOptimLikelihood <- function(p_A, p_, map_, deltaDist, epsilon, i) {
    .Call(`_Fantasio2_testOptimLikelihood`, p_A, p_, map_, deltaDist, epsilon, i)
}

testPHBDmatrix <- function(z, nbSNPs, i) {
    .Call(`_Fantasio2_testPHBDmatrix`, z, nbSNPs, i)
}

testRVector <- function(x, y, z) {
    invisible(.Call(`_Fantasio2_testRVector`, x, y, z))
}

