# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

checkOpenMP <- function() {
    .Call(`_Fantasio2_checkOpenMP`)
}

festim <- function(p_A, p, map, deltaDist, epsilon) {
    .Call(`_Fantasio2_festim`, p_A, p, map, deltaDist, epsilon)
}

forward_backward <- function(logEmiss, Dist, a, f) {
    .Call(`_Fantasio2_forward_backward`, logEmiss, Dist, a, f)
}

logLikelihood_gradient <- function(logEmiss, Dist, a, f) {
    .Call(`_Fantasio2_logLikelihood_gradient`, logEmiss, Dist, a, f)
}

logEmiss <- function(Y1, Y2, logFreq, epsilon) {
    .Call(`_Fantasio2_logEmiss`, Y1, Y2, logFreq, epsilon)
}

m4_logEmiss <- function(p_A, p, map, epsilon) {
    .Call(`_Fantasio2_m4_logEmiss`, p_A, p, map, epsilon)
}

setUserParam <- function(m, epsilon, past, delta, max_iterations, max_submin, max_linesearch, min_step, max_step, ftol, wolfe, max_retries, lower, upper, n_threads, use_float, debug) {
    invisible(.Call(`_Fantasio2_setUserParam`, m, epsilon, past, delta, max_iterations, max_submin, max_linesearch, min_step, max_step, ftol, wolfe, max_retries, lower, upper, n_threads, use_float, debug))
}

getUserParam <- function() {
    .Call(`_Fantasio2_getUserParam`)
}

testForwardBackward <- function(p_A, p_, map_, deltaDist, epsilon, i, a, f) {
    .Call(`_Fantasio2_testForwardBackward`, p_A, p_, map_, deltaDist, epsilon, i, a, f)
}

testLikelihood <- function(p_A, p_, map_, deltaDist, epsilon, i, a, f) {
    .Call(`_Fantasio2_testLikelihood`, p_A, p_, map_, deltaDist, epsilon, i, a, f)
}

testLogEmiss <- function(p_A, p_, map_, epsilon, i) {
    .Call(`_Fantasio2_testLogEmiss`, p_A, p_, map_, epsilon, i)
}

testOptimLikelihood <- function(p_A, p_, map_, deltaDist, epsilon, i) {
    .Call(`_Fantasio2_testOptimLikelihood`, p_A, p_, map_, deltaDist, epsilon, i)
}

testRVector <- function(x, y, z) {
    invisible(.Call(`_Fantasio2_testRVector`, x, y, z))
}

